// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Lc-tAciBe5q-vBnRmfs_P7rtRDxH8Lc',
    appId: '1:634788948307:web:631db47cb3ffebdde859a6',
    messagingSenderId: '634788948307',
    projectId: 'flutter-recipe-app0018',
    authDomain: 'flutter-recipe-app0018.firebaseapp.com',
    storageBucket: 'flutter-recipe-app0018.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6qEzFd8jqDm3xiXwkTRSnpk3PoLvmyuY',
    appId: '1:634788948307:android:778f0fe09e8cafa9e859a6',
    messagingSenderId: '634788948307',
    projectId: 'flutter-recipe-app0018',
    storageBucket: 'flutter-recipe-app0018.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQLMs955fP_FAtA5PEMSioYkqX1IXlX4I',
    appId: '1:634788948307:ios:28f14264024d2461e859a6',
    messagingSenderId: '634788948307',
    projectId: 'flutter-recipe-app0018',
    storageBucket: 'flutter-recipe-app0018.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQLMs955fP_FAtA5PEMSioYkqX1IXlX4I',
    appId: '1:634788948307:ios:28f14264024d2461e859a6',
    messagingSenderId: '634788948307',
    projectId: 'flutter-recipe-app0018',
    storageBucket: 'flutter-recipe-app0018.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Lc-tAciBe5q-vBnRmfs_P7rtRDxH8Lc',
    appId: '1:634788948307:web:f0afc5bba5845707e859a6',
    messagingSenderId: '634788948307',
    projectId: 'flutter-recipe-app0018',
    authDomain: 'flutter-recipe-app0018.firebaseapp.com',
    storageBucket: 'flutter-recipe-app0018.firebasestorage.app',
  );
}
